language: node_js
node_js:
- '7'
before_script:
- npm install -g gulp
- npm install --save-dev gulp
script: gulp --gulpfile ./heroku/gulpfile.js
deploy:
  provider: heroku
  api_key:
    secure: o8V/yYy59uVMYoxaIUBoS/WbmveOUapVrI2F2BcI8F2qCqszPm6JcxTK5s6y2Ui4R2QAHsN4tFMf0f3r3QIvhzp8GFkKdyo7MuMCQnPwFDWcjw5PfdJvOG5IlunfLffwYQ0V/IskWa6NGb/n3mu7MtqhYwiPcBLTIGT16YihTGOBhuwD+TsrMeswKsbv3lSAN6kPWloDrVf/iVbdUi8ALOk9uJORip3AV5utFjNPaQDzVt/aJdTrefH6yw9Wo4iLYuDm1z7rrKzmgazVcq9S9vYjUGdieDB1UKZbU9Qnd2XpiwoX8aYHW8OXbbnZrdjKeVClkVmDMoTzEYN6jlM8DzZjusHaKgVrmlfsY8LdYp0ort4Z69PohMhb/Zk9K0X5C6JM7t4kVwz2GyaS6/90D6oGLAyd+xqwMDpQPV9khvkfT6zCuPQFL3vUk5/Eynp4salIP/N2W7xcyv2NW0ru607tHsIZ5v+9X9f6rjy46xVeKsPbGutaBx7PV+Bkk8HbBaBu7MqHz51bhmZLm6fMG6INKDHQBsfMIayPDY3AhNCHuLg7RiKSv7dEfjrbdaWPTTBaRZ1PWrQ9v9JCrhLtIwz+rRVAKW+9nP3dveZCqpFlOOmZzlzhS30faEiiJRHkr8v8pZKS4+28F/IVQnrQbvMYnmRF8j2ddduYnURsq1A=
    app: p02-tfm2016mjuez