language: node_js
node_js:
- '7'
branches:
  only:
  - master
  - dev
install:
- npm install
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: g1YADbrdXDcsSQwEjGRerJCNh+cPVfcZ9TRN7NML87yotc9lacPecKd2SlDrZFpUU0kymTmesRCNLS8p71acHuWms15Gc8sG3p3a0qXjytHZsUXZStPTTTJfmS/qDzwl291EwpoXw1E0FeDgqxf2U6R6EXizuc4OkdDMycs18VALoTBxUJD8UkaGSQb9VSQ/kbHbcWrUXaLr7hieojROfuBQPwSdYiD4HXLbSQWZyZT9Zyxx4OD8QaNbdGi/+3w2CvcPb6TCCe4UxjdJDTKepU5dvGsfJi3xtp034+5Ev0J7R3f56Wb3vWQfr1oTqQdKuIpVvarH8vq5EcA37LbvPUaqVI93S21PuvdLYX8tfUz6TEtko7RHbcAeblaBqIqhxHzjX2N0wStIIbBIZieBYh+EWCNVN8Ttzxx6HjzAiA5Z9Mpkkn7uacDK3ZRAunnEaVXSGOxAomZ9ULMYqg4YWPfPGeZbFYPakPSOmRGmuiqKlXWbx+zNJQYcTSXBeC9AJFDzkB4u5/lsmmK0GHjylxH7BPDu9nI4witTZ8i3XiQ8++r2uLku6r8E2mNP3BkPIYe8ki8tEfWXLQy2ZMueNQcdvexCxKNPsxGGpAFhquNNDlTxDWCXRoazoS4Y7csNsUt+Ip27mRClE/zsrm41OSaLtpWUppfbTFalwqCu958=
  app:
    master: anvireco
    dev: anvireco-dev
env:
  secure: Bs4lfhuHL3PTjFZEp4p4kDWxQrHlLAWQ2w94NS8095IpeftnBkuia8KHeyfhpUHrBLD4wE3p/0LhwyCU7kiS4fR0I+tM3bIvCvB6AB5FVy3O0+7RhPpXfQXwL9PRjylCRT5e6b73mv3wQj+0hAM+k9GF9a12lDFpU6SGfnjK4TgjlSE0O248JhRPn5+FSff1iV/EiSGAZCPfDdVTGG8HBNepHM78cGsIG63q3XLBpk85x2B48UcgJVfp82a3wslSf3Kacc1n1PgKRI6sdLrQOZU5nelIG031sszQ7N9uT1x5jUcKRobrWr7K/Q5yQFJPHD1KzfLYdVwiAd6tLimCIxNL/DNhq4ALE9NmTO28Abj7KF4Ep4b3ZKDmEhIOE0UANosad6v9Ej9jaxJKAToMxEjIbpoILXgrc7JPOlMTarSGr0ZHzCCoLjHxHdsU1xI+W/CGnS6AlC9NZmczlGRL+zc91kxPmQCkImpvjClvN2GyPLS6rAiSQWnjWROK2Eu3iSTg1C1G17vCUP2OqeCTkE/6bYCFB4vhYO6DcvfHyW1ekh86JAJkGdX8KutY4rQPQYbIiIeHQ4oAM68fPvGXSsgc1gjBDgRjRY9gWM4dlaYyyGCJui2h3+mInbF9PeI0p2k1QyqlcjktzExQn5fflKHa9xiYjoSe/GxU5ulHAN4=
