language: node_js
node_js:
- '7'
branches:
  only:
  - master
  - dev
install:
- npm install
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: f9pssHDk1Syg07S/g+p8qDismsYKyAWq3mehca9uYCMOf6zxz+z1e2630Zk+HPpfMif+A1H5saSyKAsSdeZc6On9rKeH9uIJafZLWQw4C6j6JHjRYa8vqDFL7+o4x5kNJzAZQ43d9LT3xPGuUpbbHPoU280cjv+K7TmC5wb9uOQn5Jmzv6rvKd9iFsPBkyOUli3knd3X3yCzQ+AN9ZbhsymOqI8XHAcRtfqqkD4sRFlA62TR+5II9JJDeiG+IismTV9Lt206u32XMDgB5IV6fz40H8Nk6NAP6y4dNV346A+T4YYgQztS1f65YS0ftNy3I1Un0Ov3yA6FlLtJtmeQq6jeZ2QHVZB2umg8d4eoZmBP+ZYjrvhCL8Wp3x6aSTwuq2uR6UHgh1XdZtaGNEFhnhPy8EmRtO8bosEPWdlXhT5E+H3hTFws2hT5ulNLacgC96EOd4nZAyGjiFw6TyAwvuq6l47iUiIjFlXoTvhtWiUxHeko5JGntrdsQsblsecH/w3jmjKFCVkiM7Q3mPft1Fk0XOCuTgR90wJT8rDPBApJufzxhRS+NuZMYjscSRppW7g13wUX56WHqpNzsBhYGXl7ZkvhJN2tlWi4wreMynk+Zjnq1pICKHQWnpHmDEKtBfyY1QlngfDc9jYRhZ5UrXIwNNpotLJqQSLmS5TWNjk=
  app:
    master: anvireco
    dev: anvireco-dev
env:
  secure: Bs4lfhuHL3PTjFZEp4p4kDWxQrHlLAWQ2w94NS8095IpeftnBkuia8KHeyfhpUHrBLD4wE3p/0LhwyCU7kiS4fR0I+tM3bIvCvB6AB5FVy3O0+7RhPpXfQXwL9PRjylCRT5e6b73mv3wQj+0hAM+k9GF9a12lDFpU6SGfnjK4TgjlSE0O248JhRPn5+FSff1iV/EiSGAZCPfDdVTGG8HBNepHM78cGsIG63q3XLBpk85x2B48UcgJVfp82a3wslSf3Kacc1n1PgKRI6sdLrQOZU5nelIG031sszQ7N9uT1x5jUcKRobrWr7K/Q5yQFJPHD1KzfLYdVwiAd6tLimCIxNL/DNhq4ALE9NmTO28Abj7KF4Ep4b3ZKDmEhIOE0UANosad6v9Ej9jaxJKAToMxEjIbpoILXgrc7JPOlMTarSGr0ZHzCCoLjHxHdsU1xI+W/CGnS6AlC9NZmczlGRL+zc91kxPmQCkImpvjClvN2GyPLS6rAiSQWnjWROK2Eu3iSTg1C1G17vCUP2OqeCTkE/6bYCFB4vhYO6DcvfHyW1ekh86JAJkGdX8KutY4rQPQYbIiIeHQ4oAM68fPvGXSsgc1gjBDgRjRY9gWM4dlaYyyGCJui2h3+mInbF9PeI0p2k1QyqlcjktzExQn5fflKHa9xiYjoSe/GxU5ulHAN4=
