language: node_js
node_js:
- '7'
branches:
  only:
  - master
  - dev
install:
- npm install
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: zFlpv8Yn8Fa+BsaXgIK7zHQcZmRG/I1Wkjd6cKDfxdWjfFObn3+kPJYTMX5bT/hriCv9llz3vsTZb6cY8ecEnQMhZk93Ui01QvssmM02dHo2R0xdncm/4v7frXTqBS/VCyxHSuXlQrIOwk+G6b5Y3LfqIQvVr7ea8OTl66E3LjwrPh5E7e3cugn/ii2odmIqHof42FPC1AXBcAf+37xG9qwNL4rG1ufJLeUrf2MC9KOcXKPO5PrPT+fe1zx0weCQISUj4Zl7XRSq+hW5y3T+0h0NIygobl6Ab2lxaAb5VRHbxKL83sX8HJ1SW3k98ULY+aOCjezNahY9tJtTDwnwQjIH6nGhlyivh5IlnrLLxE4lKKUqVe+Njv8eW+Isabnx1k3Ii5prxfs8S2gHn6Kuz8Jz6RbEkvBcRoMlNZqnGw96/ymhfo/Gc5dFO5R2o2y5BEO9W4ctflUfZGLPBSM2ozovOS2vJCFJ/Ne6RtxD/uz+iO6zaov4gi12LFGUydMkATPqGEPYXyfqQ5r61yzDAYXkU/W8y0+6JIbOPwIuTyvlzrgBVB/YeQuRSBOnk6EqLS1x64xnAQzXyBgUSVyeh0eP1cZqTt1gmbK1DdtR12MI9YUUDa3UvzmMPZOCVi1aNrPtILoHiLZK/sAZJNPBBW1FSOJykP5NcQMYYZTeWtM=
  app:
    master: anvireco
    dev: anvireco-dev
env:
  secure: Bs4lfhuHL3PTjFZEp4p4kDWxQrHlLAWQ2w94NS8095IpeftnBkuia8KHeyfhpUHrBLD4wE3p/0LhwyCU7kiS4fR0I+tM3bIvCvB6AB5FVy3O0+7RhPpXfQXwL9PRjylCRT5e6b73mv3wQj+0hAM+k9GF9a12lDFpU6SGfnjK4TgjlSE0O248JhRPn5+FSff1iV/EiSGAZCPfDdVTGG8HBNepHM78cGsIG63q3XLBpk85x2B48UcgJVfp82a3wslSf3Kacc1n1PgKRI6sdLrQOZU5nelIG031sszQ7N9uT1x5jUcKRobrWr7K/Q5yQFJPHD1KzfLYdVwiAd6tLimCIxNL/DNhq4ALE9NmTO28Abj7KF4Ep4b3ZKDmEhIOE0UANosad6v9Ej9jaxJKAToMxEjIbpoILXgrc7JPOlMTarSGr0ZHzCCoLjHxHdsU1xI+W/CGnS6AlC9NZmczlGRL+zc91kxPmQCkImpvjClvN2GyPLS6rAiSQWnjWROK2Eu3iSTg1C1G17vCUP2OqeCTkE/6bYCFB4vhYO6DcvfHyW1ekh86JAJkGdX8KutY4rQPQYbIiIeHQ4oAM68fPvGXSsgc1gjBDgRjRY9gWM4dlaYyyGCJui2h3+mInbF9PeI0p2k1QyqlcjktzExQn5fflKHa9xiYjoSe/GxU5ulHAN4=
