language: node_js
node_js:
- '7'
branches:
  only:
  - master
  - dev
install:
- npm install
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: jCvULBk2e4XgbbLK5b0xaMdCXaKaGjCP0mJ9ND2IjMo8Z8R96lBtwvK+CWXIz9tyAu8YLv1mNV6Dvd1m6hIphv9miI80yrtv4Km0MTKxOWe8XiZHW3mg15D6Nq6nM/3uNCOFqUKr3q0dwjAjlzVYo8gASRIq6acUKl0gK1N9kojtqXze7HVkCLmZsYsE8MAe3UWV9gN5xj0PLFfEjU8JNuTMUKLdG/QVo7ukK+UPEOy8Qh5ADsnozW6cxQM4e7bgNVQRxc0I7ktv2MxG62Ii7T2b4LtO9jjxr4dusXSUTdHtqCbtpum0Ki1Uw+wS2myYWE5R2BzZBmAiFAeI7J17O1jf8MTiLOhZ0HyHTZmzEdxE8/Nl0L1+uHTfgEJffEwQ3Wy1OL6IMIfQp/F0AX8dZ0x1Cm7WElxBlYcn/OSivAa3A9fBYhdBSvydEhj+A/Bn2tKaeO+VV7UPezTI9AyUnIaH9vP1gJFD8Tc9u7P0DpqCp9OxKcAvPvvbmCw7JwaDI/TxRZVQB3G0GgapVBUFKFLF7+I7htBncu4JJ0HfeyK8SwelgmUELuHWSceVlGNXMEy0I5BMNWnVwUf2L03fOZ8XrA9Fdw9rpK2KiAaPPn7cKot3GulZISD+WOzABcsvFjg3UI26rHKcoY4jIjrKbmbA+SnbO9w2Eb8Bo3En8l0=
  app:
    master: anvireco
    dev: anvireco-dev
env:
  secure: Bs4lfhuHL3PTjFZEp4p4kDWxQrHlLAWQ2w94NS8095IpeftnBkuia8KHeyfhpUHrBLD4wE3p/0LhwyCU7kiS4fR0I+tM3bIvCvB6AB5FVy3O0+7RhPpXfQXwL9PRjylCRT5e6b73mv3wQj+0hAM+k9GF9a12lDFpU6SGfnjK4TgjlSE0O248JhRPn5+FSff1iV/EiSGAZCPfDdVTGG8HBNepHM78cGsIG63q3XLBpk85x2B48UcgJVfp82a3wslSf3Kacc1n1PgKRI6sdLrQOZU5nelIG031sszQ7N9uT1x5jUcKRobrWr7K/Q5yQFJPHD1KzfLYdVwiAd6tLimCIxNL/DNhq4ALE9NmTO28Abj7KF4Ep4b3ZKDmEhIOE0UANosad6v9Ej9jaxJKAToMxEjIbpoILXgrc7JPOlMTarSGr0ZHzCCoLjHxHdsU1xI+W/CGnS6AlC9NZmczlGRL+zc91kxPmQCkImpvjClvN2GyPLS6rAiSQWnjWROK2Eu3iSTg1C1G17vCUP2OqeCTkE/6bYCFB4vhYO6DcvfHyW1ekh86JAJkGdX8KutY4rQPQYbIiIeHQ4oAM68fPvGXSsgc1gjBDgRjRY9gWM4dlaYyyGCJui2h3+mInbF9PeI0p2k1QyqlcjktzExQn5fflKHa9xiYjoSe/GxU5ulHAN4=
